Comments:
    type: entity
    table: Comments
    fields:
        idcomment:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idComment
            generator:
                strategy: IDENTITY
        content:
            type: string
            length: 500
            fixed: false
            nullable: false
        createdon:
            type: datetime
            nullable: true
            column: createdOn
        uptadedon:
            type: datetime
            nullable: true
            column: uptadedOn
        isactive:
            type: boolean
            nullable: true
            column: isActive
    manyToOne:
        postspost:
            targetEntity: Posts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Posts_idPost:
                    referencedColumnName: idPost
            orphanRemoval: false
        usersuser:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Users_idUser:
                    referencedColumnName: idUser
            orphanRemoval: false
    lifecycleCallbacks: {  }
