Comment:
    type: entity
    table: comment
    fields:
        commentId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: comment_id
            generator:
                strategy: IDENTITY
        content:
            type: string
            length: 500
            fixed: false
            nullable: false
        createdOn:
            type: datetime
            nullable: true
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToOne:
        userUser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
        postPost:
            targetEntity: Post
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                post_post_id:
                    referencedColumnName: post_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
