Post:
    type: entity
    table: post
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id
            generator:
                strategy: IDENTITY
        link:
            type: string
            length: 45
            fixed: false
            nullable: false
        title:
            type: string
            length: 45
            fixed: false
            nullable: false
        shortContent:
            type: text
            nullable: false
            column: short_content
        longContent:
            type: text
            nullable: false
            column: long_content
        createdOn:
            type: datetime
            nullable: true
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToOne:
        postsCategory:
            targetEntity: PostsCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                posts_category_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        imageFile:
            targetEntity: ImageFile
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_file_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
