Posts:
    type: entity
    table: Posts
    fields:
        idPost:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idPost
            generator:
                strategy: IDENTITY
        link:
            type: string
            length: 45
            fixed: false
            nullable: false
        title:
            type: string
            length: 45
            fixed: false
            nullable: false
        shortContent:
            type: text
            nullable: false
            column: shortContent
        longContent:
            type: text
            nullable: false
            column: longContent
        createdOn:
            type: datetime
            nullable: true
            column: createdOn
        updatedOn:
            type: datetime
            nullable: true
            column: updatedOn
        isActive:
            type: boolean
            nullable: true
            column: isActive
    manyToOne:
        postsCategoriesPostsCategory:
            targetEntity: PostsCategories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PostsCategories_idPostsCategory:
                    referencedColumnName: idPostsCategory
            orphanRemoval: false
    lifecycleCallbacks: {  }
