PostsCategory:
    type: entity
    table: posts_category
    fields:
        postsCategoryId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: posts_category_id
            generator:
                strategy: IDENTITY
        categoryName:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: category_name
        link:
            type: string
            length: 45
            fixed: false
            nullable: false
        description:
            type: text
            nullable: true
        createdOn:
            type: datetime
            nullable: true
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        isActive:
            type: boolean
            nullable: true
            column: is_active
    lifecycleCallbacks: {  }
