Roles:
    type: entity
    table: Roles
    fields:
        idrole:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idRole
            generator:
                strategy: IDENTITY
        rolename:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: roleName
        createdon:
            type: datetime
            nullable: true
            column: createdOn
        uptadedon:
            type: datetime
            nullable: true
            column: uptadedOn
        isactive:
            type: boolean
            nullable: true
            column: isActive
    manyToMany:
        usersuser:
            targetEntity: Users
            cascade: {  }
            mappedBy: rolesrole
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
