Users:
    type: entity
    table: Users
    fields:
        iduser:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idUser
            generator:
                strategy: IDENTITY
        login:
            type: string
            length: 45
            fixed: false
            nullable: false
        email:
            type: string
            length: 45
            fixed: false
            nullable: false
        password:
            type: string
            length: 45
            fixed: false
            nullable: false
        firstname:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: firstName
        lastname:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: lastName
        createdon:
            type: datetime
            nullable: true
            column: createdOn
        uptadedon:
            type: datetime
            nullable: true
            column: uptadedOn
        isactive:
            type: boolean
            nullable: true
            column: isActive
    manyToMany:
        rolesrole:
            targetEntity: Roles
            cascade: {  }
            mappedBy: null
            inversedBy: usersuser
            joinTable:
                name: users_has_roles
                joinColumns:
                    -
                        name: Users_idUser
                        referencedColumnName: idUser
                inverseJoinColumns:
                    -
                        name: Roles_idRole
                        referencedColumnName: idRole
            orderBy: null
    lifecycleCallbacks: {  }
