User:
    type: entity
    table: user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id
            generator:
                strategy: IDENTITY
        login:
            type: string
            length: 45
            fixed: false
            nullable: false
        email:
            type: string
            length: 45
            fixed: false
            nullable: false
        password:
            type: string
            length: 128
            fixed: false
            nullable: false
        firstName:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: last_name
        createdOn:
            type: datetime
            nullable: true
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToMany:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_has_role
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
