admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
login:
    path:   /login
    defaults:  { _controller: HomepageBlogBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
    
homepage_blog:
    resource: "@HomepageBlogBundle/Resources/config/routing.yml"
    prefix:   /