nerdlab_blog_index:
    pattern:  /
    defaults: { _controller: NerdLabBlogBundle:Blog:index, page:1 }
nerdlab_blog_index_page:
    pattern:  /page/{page}/
    defaults: { _controller: NerdLabBlogBundle:Blog:index }
    requirements:
        page:  \d+
nerdlab_blog_category:
    pattern:  /category/{category}/
    defaults: { _controller: NerdLabBlogBundle:Blog:index, page:1 }
nerdlab_blog_category_page:
    pattern:  /category/{category}/page/{page}/
    defaults: { _controller: NerdLabBlogBundle:Blog:index }
    requirements:
        page:  \d+
    
nerdlab_blog_user_edit:
    pattern:  /user/{login}/edit/
    defaults: { _controller: NerdLabBlogBundle:User:edit }
nerdlab_blog_user_view:
    pattern:  /user/{login}/
    defaults: { _controller: NerdLabBlogBundle:User:view }
nerdlab_blog_user_author:
    pattern:  /author/{login}/
    defaults: { _controller: NerdLabBlogBundle:User:viewAuthor }
nerdlab_blog_user_create:
    pattern:  /register/
    defaults: { _controller: NerdLabBlogBundle:User:create }
nerdlab_blog_user_activate:
    pattern:  /activate/
    defaults: { _controller: NerdLabBlogBundle:User:activate }
nerdlab_blog_contact:
    pattern:  /kontakt/
    defaults: { _controller: NerdLabBlogBundle:Contact:contact }
    
nerdlab_blog_psw_edit:
    pattern:  /user/{login}/edit/change-password/
    defaults: { _controller: NerdLabBlogBundle:Password:changePsw }
nerdlab_blog_psw_reset:
    pattern:  /reset-password/
    defaults: { _controller: NerdLabBlogBundle:Password:resetPsw }
nerdlab_blog_psw_forgotten:
    pattern:  /forgotten-password/
    defaults: { _controller: NerdLabBlogBundle:Password:forgottenPsw } 

nerdlab_blog_cookies:
    path: /polityka-cookies/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NerdLabBlogBundle:Static:cookies-policy.html.twig'
               
nerdlab_blog_rss:
    pattern:  /rss.xml
    defaults: { _controller: NerdLabBlogBundle:XmlGenerator:rss }
    
nerdlab_blog_upload_image:
    pattern:  /upload-image
    defaults: { _controller: NerdLabBlogBundle:File:uploadImage }

nerdlab_blog_post_create:
    pattern:  /create-post/
    defaults: { _controller: NerdLabBlogBundle:Post:createPost }
nerdlab_blog_post:
    pattern:  /{link}/
    defaults: { _controller: NerdLabBlogBundle:Post:showPost }
nerdlab_blog_post_edit:
    pattern:  /{link}/edit/
    defaults: { _controller: NerdLabBlogBundle:Post:editPost }

