parameters:
#    nerdlab_blog.example.class: NerdLab\BlogBundle\Example

services:
#    nerdlab_blog.example:
#        class: %nerdlab_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
