homepage_blog_index:
    pattern:  /
    defaults: { _controller: HomepageBlogBundle:Blog:index, page:0 }
homepage_blog_index_page:
    pattern:  /page/{page}.html
    defaults: { _controller: HomepageBlogBundle:Blog:index }
homepage_blog_posts:
    pattern:  /post/{link}
    defaults: { _controller: HomepageBlogBundle:Post:showPost }
homepage_blog_psw_edit:
    pattern:  /user/{login}/edit/changepsw
    defaults: { _controller: HomepageBlogBundle:Password:changePsw }
homepage_blog_psw_reset:
    pattern:  /reset-password
    defaults: { _controller: HomepageBlogBundle:Password:resetPsw }
homepage_blog_psw_forgotten:
    pattern:  /forgotten-password
    defaults: { _controller: HomepageBlogBundle:Password:forgottenPsw }
homepage_blog_user_view:
    pattern:  /user/{login}/view/
    defaults: { _controller: HomepageBlogBundle:User:index }
homepage_blog_user_edit:
    pattern:  /user/{login}/edit/
    defaults: { _controller: HomepageBlogBundle:User:edit }
homepage_blog_user_create:
    pattern:  /register/
    defaults: { _controller: HomepageBlogBundle:User:create }
homepage_blog_user_activate:
    pattern:  /activate/
    defaults: { _controller: HomepageBlogBundle:User:activate }
