homepage_blog_index:
    pattern:  /
    defaults: { _controller: HomepageBlogBundle:Blog:index, page:0 }
homepage_blog_index_page:
    pattern:  /page/{page}/
    defaults: { _controller: HomepageBlogBundle:Blog:index }
homepage_blog_category:
    pattern:  /category/{category}/
    defaults: { _controller: HomepageBlogBundle:Blog:index, page:0 }
homepage_blog_category_page:
    pattern:  /category/{category}/page/{page}/
    defaults: { _controller: HomepageBlogBundle:Blog:index }
    
homepage_blog_user_edit:
    pattern:  /user/{login}/edit/
    defaults: { _controller: HomepageBlogBundle:User:edit }
homepage_blog_user_view:
    pattern:  /user/{login}/
    defaults: { _controller: HomepageBlogBundle:User:view }
homepage_blog_user_author:
    pattern:  /author/{login}/
    defaults: { _controller: HomepageBlogBundle:User:viewAuthor }
homepage_blog_user_create:
    pattern:  /register/
    defaults: { _controller: HomepageBlogBundle:User:create }
homepage_blog_user_activate:
    pattern:  /activate/
    defaults: { _controller: HomepageBlogBundle:User:activate }
homepage_blog_contact:
    pattern:  /kontakt/
    defaults: { _controller: HomepageBlogBundle:Contact:contact }
    
homepage_blog_psw_edit:
    pattern:  /user/{login}/edit/change-password/
    defaults: { _controller: HomepageBlogBundle:Password:changePsw }
homepage_blog_psw_reset:
    pattern:  /reset-password/
    defaults: { _controller: HomepageBlogBundle:Password:resetPsw }
homepage_blog_psw_forgotten:
    pattern:  /forgotten-password/
    defaults: { _controller: HomepageBlogBundle:Password:forgottenPsw } 

homepage_blog_cookies:
    path: /polityka-cookies/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'HomepageBlogBundle:Static:cookies-policy.html.twig'
               
homepage_blog_rss:
    pattern:  /rss.xml
    defaults: { _controller: HomepageBlogBundle:XmlGenerator:rss }
    
homepage_blog_upload_image:
    pattern:  /upload-image
    defaults: { _controller: HomepageBlogBundle:File:uploadImage }

homepage_blog_post_create:
    pattern:  /create-post/
    defaults: { _controller: HomepageBlogBundle:Post:createPost }
homepage_blog_post:
    pattern:  /{link}/
    defaults: { _controller: HomepageBlogBundle:Post:showPost }
homepage_blog_post_edit:
    pattern:  /{link}/edit/
    defaults: { _controller: HomepageBlogBundle:Post:editPost }

