homepage_blog_index:
    pattern:  /
    defaults: { _controller: HomepageBlogBundle:Default:index, page:0 }
homepage_blog_index_page:
    pattern:  /page/{page}.html
    defaults: { _controller: HomepageBlogBundle:Default:index }
homepage_blog_posts:
    pattern:  /post/{link}
    defaults: { _controller: HomepageBlogBundle:Post:showPost }
homepage_blog_user_edit:
    pattern:  /user/{login}/edit/
    defaults: { _controller: HomepageBlogBundle:User:edit }
homepage_blog_user_edit_psw:
    pattern:  /user/{login}/edit/changepsw
    defaults: { _controller: HomepageBlogBundle:User:changePsw }
homepage_blog_user_reset_psw:
    pattern:  /resetpassword
    defaults: { _controller: HomepageBlogBundle:User:resetPsw }
homepage_blog_user_view:
    pattern:  /user/{login}/view/
    defaults: { _controller: HomepageBlogBundle:User:index }
homepage_blog_user_create:
    pattern:  /register/
    defaults: { _controller: HomepageBlogBundle:User:create }
homepage_blog_user_activate:
    pattern:  /activate/
    defaults: { _controller: HomepageBlogBundle:User:activate }
