parameters:
#    homepage_blog.example.class: Homepage\BlogBundle\Example

services:
#    homepage_blog.example:
#        class: %homepage_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
