Homepage\BlogBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: email
            message: The email is already used.
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: login
            message: The login is already used.
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: Email "{{ value }}" nie jest prawidłowy.
                checkMX: true
        login:
            - NotBlank: ~
        password:
            - NotBlank: ~
            - Length:
                min: 8
                minMessage: "Hasło nie może być krótsze niż {{ limit }} znaków."
                
Homepage\BlogBundle\Form\Model\ChangePassword:
    properties:
        oldPassword:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: "Wprowadziłeś złe aktualne hasło."
        newPassword:
            - NotBlank: ~
            - Length:
                min: 8
                minMessage: "Hasło nie może być krótsze niż {{ limit }} znaków."
                
Homepage\BlogBundle\Form\Model\ForgottenPassword:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: Email "{{ value }}" nie jest prawidłowy.
                checkMX: true